/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/nav/AboutMe': RouteRecordInfo<'/nav/AboutMe', '/nav/AboutMe', Record<never, never>, Record<never, never>>,
    '/nav/ContactMe': RouteRecordInfo<'/nav/ContactMe', '/nav/ContactMe', Record<never, never>, Record<never, never>>,
    '/nav/Home': RouteRecordInfo<'/nav/Home', '/nav/Home', Record<never, never>, Record<never, never>>,
    '/nav/LittleTools': RouteRecordInfo<'/nav/LittleTools', '/nav/LittleTools', Record<never, never>, Record<never, never>>,
    '/nav/Lw': RouteRecordInfo<'/nav/Lw', '/nav/Lw', Record<never, never>, Record<never, never>>,
    '/nav/PhotoWall': RouteRecordInfo<'/nav/PhotoWall', '/nav/PhotoWall', Record<never, never>, Record<never, never>>,
    '/nav/projectBoard': RouteRecordInfo<'/nav/projectBoard', '/nav/projectBoard', Record<never, never>, Record<never, never>>,
    '/nav/Thoughts': RouteRecordInfo<'/nav/Thoughts', '/nav/Thoughts', Record<never, never>, Record<never, never>>,
    '/nav/Tools/colorChina': RouteRecordInfo<'/nav/Tools/colorChina', '/nav/Tools/colorChina', Record<never, never>, Record<never, never>>,
    '/nav/Tools/gaokao': RouteRecordInfo<'/nav/Tools/gaokao', '/nav/Tools/gaokao', Record<never, never>, Record<never, never>>,
    '/nav/Tools/keyboard': RouteRecordInfo<'/nav/Tools/keyboard', '/nav/Tools/keyboard', Record<never, never>, Record<never, never>>,
    '/nav/Tools/regexDoctor': RouteRecordInfo<'/nav/Tools/regexDoctor', '/nav/Tools/regexDoctor', Record<never, never>, Record<never, never>>,
    '/nav/Tools/uuid': RouteRecordInfo<'/nav/Tools/uuid', '/nav/Tools/uuid', Record<never, never>, Record<never, never>>,
  }
}
