/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/nav/AboutMe': RouteRecordInfo<
      '/nav/AboutMe',
      '/nav/AboutMe',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/nav/Ai': RouteRecordInfo<
      '/nav/Ai',
      '/nav/Ai',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/nav/ContactMe': RouteRecordInfo<
      '/nav/ContactMe',
      '/nav/ContactMe',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/nav/Home': RouteRecordInfo<
      '/nav/Home',
      '/nav/Home',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/nav/LittleTools': RouteRecordInfo<
      '/nav/LittleTools',
      '/nav/LittleTools',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/nav/Lw': RouteRecordInfo<
      '/nav/Lw',
      '/nav/Lw',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/nav/PhotoWall': RouteRecordInfo<
      '/nav/PhotoWall',
      '/nav/PhotoWall',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/nav/projectBoard': RouteRecordInfo<
      '/nav/projectBoard',
      '/nav/projectBoard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/nav/Thoughts': RouteRecordInfo<
      '/nav/Thoughts',
      '/nav/Thoughts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/nav/Tools/colorChina': RouteRecordInfo<
      '/nav/Tools/colorChina',
      '/nav/Tools/colorChina',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/nav/Tools/colorJapan': RouteRecordInfo<
      '/nav/Tools/colorJapan',
      '/nav/Tools/colorJapan',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/nav/Tools/gaokao': RouteRecordInfo<
      '/nav/Tools/gaokao',
      '/nav/Tools/gaokao',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/nav/Tools/keyboard': RouteRecordInfo<
      '/nav/Tools/keyboard',
      '/nav/Tools/keyboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/nav/Tools/regexDoctor': RouteRecordInfo<
      '/nav/Tools/regexDoctor',
      '/nav/Tools/regexDoctor',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/nav/Tools/uuid': RouteRecordInfo<
      '/nav/Tools/uuid',
      '/nav/Tools/uuid',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/nav/AboutMe.vue': {
      routes:
        | '/nav/AboutMe'
      views:
        | never
    }
    'src/pages/nav/Ai.vue': {
      routes:
        | '/nav/Ai'
      views:
        | never
    }
    'src/pages/nav/ContactMe.vue': {
      routes:
        | '/nav/ContactMe'
      views:
        | never
    }
    'src/pages/nav/Home.vue': {
      routes:
        | '/nav/Home'
      views:
        | never
    }
    'src/pages/nav/LittleTools.vue': {
      routes:
        | '/nav/LittleTools'
      views:
        | never
    }
    'src/pages/nav/Lw.vue': {
      routes:
        | '/nav/Lw'
      views:
        | never
    }
    'src/pages/nav/PhotoWall.vue': {
      routes:
        | '/nav/PhotoWall'
      views:
        | never
    }
    'src/pages/nav/projectBoard.vue': {
      routes:
        | '/nav/projectBoard'
      views:
        | never
    }
    'src/pages/nav/Thoughts.vue': {
      routes:
        | '/nav/Thoughts'
      views:
        | never
    }
    'src/pages/nav/Tools/colorChina.vue': {
      routes:
        | '/nav/Tools/colorChina'
      views:
        | never
    }
    'src/pages/nav/Tools/colorJapan.vue': {
      routes:
        | '/nav/Tools/colorJapan'
      views:
        | never
    }
    'src/pages/nav/Tools/gaokao.vue': {
      routes:
        | '/nav/Tools/gaokao'
      views:
        | never
    }
    'src/pages/nav/Tools/keyboard.vue': {
      routes:
        | '/nav/Tools/keyboard'
      views:
        | never
    }
    'src/pages/nav/Tools/regexDoctor.vue': {
      routes:
        | '/nav/Tools/regexDoctor'
      views:
        | never
    }
    'src/pages/nav/Tools/uuid.vue': {
      routes:
        | '/nav/Tools/uuid'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
